
import React from 'react';

const Privacy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-24">
      <h1 className="text-6xl font-serif-brand text-[#3D1F00] mb-10 italic">Privacy Policy</h1>
      <p className="text-slate-400 mb-12 font-medium tracking-wide uppercase text-xs font-mono">Last updated: December 19, 2025</p>
      
      <div className="space-y-12 text-slate-600 leading-relaxed font-light text-lg">
        <section className="space-y-4">
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
        </section>

        <section className="space-y-6">
          <h2 className="text-3xl font-serif-brand text-[#3D1F00] italic">Interpretation and Definitions</h2>
          
          <div className="space-y-6">
            <div>
              <h3 className="text-xl font-bold text-[#3D1F00] mb-2">Interpretation</h3>
              <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            </div>

            <div>
              <h3 className="text-xl font-bold text-[#3D1F00] mb-4">Definitions</h3>
              <p className="mb-4">For the purposes of this Privacy Policy:</p>
              <ul className="list-disc pl-6 space-y-4">
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Application</strong> refers to Outvibe, the software program provided by the Company.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to OUTVIBE TECH PRIVATE LIMITED, Door Number 2-10, Adepila House, Shamboor Post, Bantwal Taluk, Mangalore 574231, Karnataka, India.</li>
                <li><strong>Country</strong> refers to: Karnataka, India</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Application.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
              </ul>
            </div>
          </div>
        </section>

        <section className="space-y-8">
          <h2 className="text-3xl font-serif-brand text-[#3D1F00] italic">Collecting and Using Your Personal Data</h2>
          
          <div className="space-y-6">
            <h3 className="text-xl font-bold text-[#3D1F00]">Types of Data Collected</h3>
            
            <div className="space-y-4">
              <h4 className="font-bold text-slate-900">Personal Data</h4>
              <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Payment-related information (such as transaction details, purchase history, and billing address)</li>
                <li>Usage Data</li>
              </ul>
            </div>

            <div className="space-y-4">
              <h4 className="font-bold text-slate-900">Usage Data</h4>
              <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device's IP address, browser type, the pages of our Service that You visit, the time and date of Your visit, and other diagnostic data.</p>
            </div>

            <div className="space-y-4">
              <h4 className="font-bold text-slate-900">Information Collected while Using the Application</h4>
              <p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Information regarding your location</li>
                <li>Information from your Device's phone book (contacts list)</li>
                <li>Pictures and other information from your Device's camera and photo library</li>
              </ul>
              <p>We use this information to provide features of Our Service, to improve and customize Our Service. You can enable or disable access at any time through Your Device settings.</p>
            </div>
          </div>
        </section>

        <section className="space-y-6">
          <h2 className="text-3xl font-serif-brand text-[#3D1F00] italic">Use of Your Personal Data</h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc pl-6 space-y-4">
            <li><strong>To provide and maintain our Service:</strong> including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for products or services.</li>
            <li><strong>To contact You:</strong> regarding updates or informative communications related to functionalities or security updates.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong>For business transfers:</strong> to evaluate or conduct a merger, divestiture, restructuring, or reorganization.</li>
            <li><strong>For other purposes:</strong> such as data analysis, identifying usage trends, and to evaluate and improve our Service.</li>
          </ul>
        </section>

        <section className="space-y-6">
          <h2 className="text-3xl font-serif-brand text-[#3D1F00] italic">Payments</h2>
          <div className="space-y-4">
            <p>If You choose to purchase any products or services through the Service, We may use third-party payment processors to handle payments.</p>
            <p>We do not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their respective Privacy Policies.</p>
            <p>These payment processors adhere to standards set by PCI-DSS as managed by the PCI Security Standards Council, which helps ensure the secure handling of payment information.</p>
            <p>We may receive limited information related to Your payment such as payment confirmation, transaction ID, amount paid, and purchase status, which is used only to provide and maintain the Service.</p>
          </div>
        </section>

        <section className="space-y-6">
          <h2 className="text-3xl font-serif-brand text-[#3D1F00] italic">Retention and Transfer</h2>
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.</p>
        </section>

        <section className="space-y-6">
          <h2 className="text-3xl font-serif-brand text-[#3D1F00] italic">Delete Your Personal Data</h2>
          <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service or by contacting us directly.</p>
        </section>

        <section className="space-y-6">
          <h2 className="text-3xl font-serif-brand text-[#3D1F00] italic">Security of Your Personal Data</h2>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
        </section>

        <section className="space-y-6">
          <h2 className="text-3xl font-serif-brand text-[#3D1F00] italic">Children's Privacy</h2>
          <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
        </section>

        <section className="p-10 bg-orange-50 rounded-[3rem] border border-orange-100">
          <h2 className="text-3xl font-serif-brand text-[#3D1F00] mb-6 italic text-center">Contact Us</h2>
          <p className="text-center mb-6">If you have any questions about this Privacy Policy, You can contact us:</p>
          <div className="flex justify-center">
            <a href="mailto:outvibesocial@gmail.com" className="text-2xl font-bold text-[#FF6B00] hover:underline decoration-2 underline-offset-8">
              outvibesocial@gmail.com
            </a>
          </div>
        </section>
      </div>
    </div>
  );
};

export default Privacy;
